# Generated by Django 5.2.17 on 2026-09-25 11:46

import aviaticket.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]{2}$",
                                "Две заглавные буквы или цифры, например SU.",
                            )
                        ],
                        verbose_name="код IATA",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1909),
                            django.core.validators.MaxValueValidator(
                                aviaticket.models.current_year
                            ),
                        ],
                        verbose_name="год основания",
                    ),
                ),
            ],
            options={
                "verbose_name": "авиакомпания",
                "verbose_name_plural": "авиакомпании",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Три заглавные латинские буквы, например MOW.",
                            )
                        ],
                        verbose_name="код IATA",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="cities/", verbose_name="фотография"
                    ),
                ),
            ],
            options={
                "verbose_name": "город",
                "verbose_name_plural": "города",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Например, SU 1402",
                        max_length=8,
                        verbose_name="номер рейса",
                    ),
                ),
                ("departure_at", models.DateTimeField(verbose_name="вылет")),
                (
                    "duration",
                    models.DurationField(
                        help_text="Формат: ЧЧ:ММ:СС", verbose_name="время в пути"
                    ),
                ),
                (
                    "transfers",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="пересадки"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="цена, ₽",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False, max_length=64, unique=True, verbose_name="слаг"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="aviaticket.airline",
                        verbose_name="авиакомпания",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="aviaticket.city",
                        verbose_name="куда",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="aviaticket.city",
                        verbose_name="откуда",
                    ),
                ),
            ],
            options={
                "verbose_name": "рейс",
                "verbose_name_plural": "рейсы",
                "ordering": ["departure_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Оформлен"), ("cancelled", "Отменён")],
                        default="confirmed",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "pnr",
                    models.CharField(
                        default=aviaticket.models.generate_pnr,
                        editable=False,
                        max_length=6,
                        unique=True,
                        verbose_name="номер бронирования",
                    ),
                ),
                ("seat", models.CharField(max_length=4, verbose_name="место")),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Цена на момент покупки", verbose_name="стоимость, ₽"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="оформлен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменён"),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="aviaticket.flight",
                        verbose_name="рейс",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пассажир",
                    ),
                ),
            ],
            options={
                "verbose_name": "билет",
                "verbose_name_plural": "билеты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", models.F("destination")), _negated=True),
                name="flight_origin_differs_from_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__gt", datetime.timedelta(0))),
                name="flight_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "passenger"),
                name="one_ticket_per_passenger_per_flight",
            ),
        ),
    ]
