# Generated by Django 5.1.4 on 2024-12-18 09:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1910), django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_from', models.CharField(max_length=50, verbose_name='Откуда')),
                ('flight_to', models.CharField(max_length=50, verbose_name='Куда')),
                ('time_in_flight', models.DateTimeField(verbose_name='Время в пути')),
                ('day_of_departure', models.DateField(verbose_name='Дата вылета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('amount_of_transfers', models.IntegerField(blank=True, null=True, verbose_name='Количество пересадок')),
                ('time_created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='aviaticket.airline', verbose_name='Авиакомпания')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Забронирован'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('completed', 'Завершен')], default='booked', max_length=20, verbose_name='Статус билета')),
                ('booking_reference', models.CharField(max_length=50, unique=True, verbose_name='Номер бронирования')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_card', to='aviaticket.flight')),
            ],
        ),
    ]
