# Generated by Django 5.1.4 on 2024-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaticket', '0003_alter_airline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Слаг'),
        ),
    ]
