# Generated by Django 5.1.4 on 2024-12-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaticket', '0004_flight_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='aviaticket.flight'),
        ),
    ]
