# Generated by Django 5.1.4 on 2024-12-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaticket', '0005_alter_flight_slug_alter_ticket_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWithPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=55, unique=True, verbose_name='Название города')),
                ('photo', models.FileField(upload_to='media_photo_city', verbose_name='Фотография города')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото города прибытия'),
        ),
    ]
